version: '3.8'

services:
  rpk-faucet-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpk-faucet-web
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
